# Generated by Django 6.0.1 on 2026-02-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="quantity_grams",
        ),
        migrations.AddField(
            model_name="recipe",
            name="calories",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="quantity",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(default="g", max_length=50),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="prep_time_mins",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
