# Generated by Django 6.0.1 on 2026-03-02 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_recipeingredient_quantity_grams_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("country", models.CharField(max_length=100)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("primary_goal", models.CharField(blank=True, max_length=50)),
                ("activity_level", models.CharField(blank=True, max_length=50)),
                ("dietary_preference", models.CharField(default="None", max_length=50)),
                ("meals_per_day", models.IntegerField(default=3)),
                ("allergies", models.JSONField(blank=True, default=list)),
                ("foods_to_avoid", models.JSONField(blank=True, default=list)),
                ("medical_conditions", models.JSONField(blank=True, default=list)),
                ("medications", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="consultationrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="weeklyplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.userprofile"
            ),
        ),
        migrations.DeleteModel(
            name="RegularUserProfile",
        ),
    ]
