# Generated by Django 6.0.1 on 2026-03-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userprofile_target_calories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyplan",
            name="target_water_ml",
            field=models.IntegerField(default=2500),
        ),
        migrations.AddField(
            model_name="dailyplan",
            name="water_consumed_ml",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mealslot",
            name="is_consumed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.IntegerField(
                default=0, help_text="Consecutive days logging in/eating meals"
            ),
        ),
    ]
