# Generated by Django 6.0.1 on 2026-03-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_dailyplan_target_water_ml_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="target_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mealslot",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("B", "Breakfast"),
                    ("S1", "Morning Snack"),
                    ("L", "Lunch"),
                    ("S2", "Mid Day Snack"),
                    ("D", "Dinner"),
                ],
                max_length=5,
            ),
        ),
    ]
