# Generated by Django 6.0.1 on 2026-03-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_userprofile_target_weight_alter_mealslot_meal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("PATIENT", "Patient"), ("DIETITIAN", "Dietitian")],
                default="PATIENT",
                max_length=15,
            ),
        ),
    ]
