# Generated by Django 6.0.3 on 2026-03-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_userprofile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_picture",
        ),
    ]
