# Generated by Django 6.0.3 on 2026-03-21 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_appointment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dietitianreview",
            unique_together={("patient", "dietitian")},
        ),
        migrations.AddField(
            model_name="dietitianreview",
            name="call_quality_rating",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="dietitianreview",
            name="dietitian_rating",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="dietitianreview",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="SystemNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT", "Appointment Alert"),
                            ("QUESTIONNAIRE", "Questionnaire Alert"),
                            ("GENERAL", "General System Alert"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dietitian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="dietitianreview",
            name="rating",
        ),
    ]
