# Generated by Django 6.0.3 on 2026-03-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_patientnote_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_active_date",
            field=models.DateField(
                blank=True, help_text="The last date the streak was updated", null=True
            ),
        ),
    ]
