### 1. Login to get your Token
POST https://grist-diet-app-production.up.railway.app/api/login/
Content-Type: application/json

{
  "username": "andy_jonson",
  "password": "20080903Mahee!"
}

> {%
    // This script catches the token from your live server and saves it!
    client.global.set("auth_token", response.body.access);
%}
### 2. Request a Morning Snack (S1)
GET https://grist-diet-app-production.up.railway.app/api/recipe/request/?type=s1
Authorization: Bearer {{auth_token}}
Accept: application/json

### Test Google Auth Endpoint (The Bouncer Test)
POST https://grist-diet-app-production.up.railway.app/api/auth/google/
Content-Type: application/json

{
  "id_token": "this_is_a_completely_fake_token_to_test_the_bouncer"
}